theme: jekyll-theme-primer
title: AI-Powered Open-Source Infrastructure for Accelerating Materials Discovery and Advanced Manufacturing
description: Tools, datasets, and platforms referenced in the associated research work
baseurl: "/ai-infrastructure-for-materials-discovery"
